service: pizza-shop

plugins:
  - serverless-iam-roles-per-function

package:
  exclude:
    - '**/**'
  include:
    - ./.bin/**

provider:
  name: aws
  runtime: go1.x
  versionFunctions: false
  stage: ${opt:stage, self:custom.defaultStage}

functions:
  # Infrastructure
  - ${file(lambda/infrastructure/functions.yml)}

  # Order API
  - ${file(lambda/order/functions.yml)}

resources:
  # Infrastructure - EventTable, EventRepository, and EventBus
  - ${file(lambda/infrastructure/resources.yml)}

  # Order - OrderTable
  - ${file(lambda/order/resources.yml)}