EventForwarder:
  handler: ./.bin/infrastructure_eventforwarder
  package:
    include:
      - ./.bin/infrastructure_eventforwarder
  events:
    - stream: 
        type: dynamodb
        arn: !GetAtt EventsTable.StreamArn
        startingPosition: LATEST
  environment:
    EVENT_BUS: !Ref EventBus
    BUCKET_NAME: !Ref EventRepository
  iamRoleStatementsName: 'EventForwarderRole-${opt:stage}'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
      Resource: '*'
    - Effect: "Allow"        
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams   
      Resource: !GetAtt EventsTable.StreamArn
    - Effect: "Allow"        
      Action:
        - SNS:Publish       
      Resource: !Ref EventBus
    - Effect: Allow
      Action:
        - s3Store:PutObject
      Resource:
        - !GetAtt EventRepository.Arn
        - !Join
            - '/'
            - - !GetAtt EventRepository.Arn
              - '*'