Resources:
  # DynamoDB Table
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EventsTable-${opt:stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: aggregateId
          AttributeType: S
        - AttributeName: aggregateSequence
          AttributeType: N
      KeySchema:
        - AttributeName: aggregateId
          KeyType: HASH
        - AttributeName: aggregateSequence
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      
  # S3 Bucket
  EventRepository:
    Type: AWS::S3::Bucket

  # Event Topic
  EventBus:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: EventBus-${opt:stage}