Resources:
  # DynamoDB Tables
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EventsTable-${opt:stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: aggregateId
          AttributeType: S
        - AttributeName: aggregateSequence
          AttributeType: N
      KeySchema:
        - AttributeName: aggregateId
          KeyType: HASH
        - AttributeName: aggregateSequence
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  SagaStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SagaStateTable-${opt:stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sagaId
          AttributeType: S
      KeySchema:
        - AttributeName: sagaId
          KeyType: HASH

  SagaAssociationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SagaAssociationTable-${opt:stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: associationId
          AttributeType: S
        - AttributeName: sagaType
          AttributeType: S
      KeySchema:
        - AttributeName: associationId
          KeyType: HASH
        - AttributeName: sagaType
          KeyType: RANGE
      
  # S3 Bucket
  EventRepository:
    Type: AWS::S3::Bucket

  # Event Topic
  EventBus:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: EventBus-${opt:stage}